# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tguedes <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/08/20 11:18:31 by tguedes           #+#    #+#              #
#    Updated: 2018/08/20 11:54:13 by tguedes          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = do-op
FLAGS = -Wall -Wextra -Werror

SRCS = srcs/do_op.c srcs/ft_atoi.c srcs/ft_error.c srcs/ft_putchar.c srcs/ft_putnbr.c srcs/ft_calcul.c

$(NAME):
	@gcc $(FLAGS) -o $(NAME) $(SRCS)

clear:
	@clear

fclear:
	@rm -rf $(NAME)

all:
	$(NAME)
